import { User } from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "1",
    name: "Alex Johnson",
    department: "Computer",
    faculty: "Engineering",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 3,
    skillsTeach: ["Python", "React Native", "UI Design"],
    skillsLearn: ["Guitar", "French"],
    engagementScore: 850,
    weeklyGain: 45,
    achievements: ["💻 Coding Wizard", "🎨 Design Tutor"],
    avatar: undefined,
  },
  {
    id: "2",
    name: "Sarah Chen",
    department: "Theater",
    faculty: "Arts",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 2,
    skillsTeach: ["Digital Illustration", "Piano"],
    skillsLearn: ["Coding", "Business Strategy"],
    engagementScore: 720,
    weeklyGain: 30,
    achievements: ["🎨 Design Tutor"],
    avatar: "https://i.pravatar.cc/150?u=2",
  },
  {
    id: "3",
    name: "Marcus Miller",
    department: "Maths",
    faculty: "Science",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 4,
    skillsTeach: ["Physics", "Mathematics"],
    skillsLearn: ["Public Speaking", "Chess"],
    engagementScore: 910,
    weeklyGain: 60,
    achievements: ["🔬 Science Sage"],
    avatar: "https://i.pravatar.cc/150?u=3",
  },
  {
    id: "4",
    name: "Elena Rodriguez",
    department: "Economics",
    faculty: "Business",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 1,
    skillsTeach: ["Marketing", "Excel"],
    skillsLearn: ["Graphic Design", "Video Editing"],
    engagementScore: 540,
    weeklyGain: 20,
    achievements: ["💼 Business Pro"],
    avatar: "https://i.pravatar.cc/150?u=4",
  },
  {
    id: "5",
    name: "David Smith",
    department: "Vetenary",
    faculty: "Medical",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 5,
    skillsTeach: ["Anatomy", "First Aid"],
    skillsLearn: ["Photography", "Spanish"],
    engagementScore: 680,
    weeklyGain: 15,
    achievements: ["🏥 Life Saver"],
    avatar: "https://i.pravatar.cc/150?u=5",
  },
  {
    id: "6",
    name: "Maya Patel",
    department: "Human Kinetics",
    faculty: "Education",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 3,
    skillsTeach: ["Teaching Methods", "Public Speaking"],
    skillsLearn: ["Python", "Data Analysis"],
    engagementScore: 790,
    weeklyGain: 50,
    achievements: ["🎓 Master Mentor"],
    avatar: "https://i.pravatar.cc/150?u=6",
  },
  {
    id: "7",
    name: "Kevin Lee",
    department: "Mechatronics",
    faculty: "Engineering",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 2,
    skillsTeach: ["C++", "Robotics"],
    skillsLearn: ["Piano", "Cooking"],
    engagementScore: 610,
    weeklyGain: 25,
    achievements: ["🤖 Robot Builder"],
    avatar: "https://i.pravatar.cc/150?u=7",
  },
  {
    id: "8",
    name: "Jessica Taylor",
    department: "Fine Arts",
    faculty: "Arts",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 4,
    skillsTeach: ["Sculpting", "Art History"],
    skillsLearn: ["Marketing", "Web Dev"],
    engagementScore: 480,
    weeklyGain: 10,
    achievements: ["🗿 Artiste"],
    avatar: "https://i.pravatar.cc/150?u=8",
  },
  {
    id: "9",
    name: "Ryan White",
    department: "Biochemistry",
    faculty: "Science",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 3,
    skillsTeach: ["Chemistry", "Lab Safety"],
    skillsLearn: ["Guitar", "Fitness"],
    engagementScore: 320,
    weeklyGain: 5,
    achievements: ["🧪 Chemist"],
    avatar: "https://i.pravatar.cc/150?u=9",
  },
  {
    id: "10",
    name: "Sophia Brown",
    department: "Food and Nutrition",
    faculty: "Medical",
    phone: "[Phone Number]",
    email: "[EMAIL_ADDRESS]",
    matric: "U23CO2014",
    year: 2,
    skillsTeach: ["Yoga", "Nutrition"],
    skillsLearn: ["Coding", "Painting"],
    engagementScore: 890,
    weeklyGain: 70,
    achievements: ["🧘 Zen Master", "🍎 Health Guru"],
    avatar: "https://i.pravatar.cc/150?u=10",
  },
];
